controller_manager_ns: moveit_simple_controller_manager
controller_list:
  - name: simulation/right_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
      
  - name: simulation/left_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
 
  - name: simulation/left_sdh
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_sdh_knuckle_joint 
      - left_sdh_finger_12_joint
      - left_sdh_finger_13_joint
      - left_sdh_finger_22_joint
      - left_sdh_finger_23_joint
      - left_sdh_thumb_2_joint
      - left_sdh_thumb_3_joint
      
  - name: simulation/right_sdh
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_sdh_knuckle_joint 
      - right_sdh_finger_12_joint
      - right_sdh_finger_13_joint
      - right_sdh_finger_22_joint
      - right_sdh_finger_23_joint
      - right_sdh_thumb_2_joint
      - right_sdh_thumb_3_joint