joint_limits:
  left_sdh_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  head_neck_pitch_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  left_sdh_finger_22_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_sdh_finger_12_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_sdh_finger_12_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_sdh_finger_22_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  head_left_eye_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  head_right_eye_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  right_sdh_thumb_3_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  right_sdh_finger_13_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_sdh_thumb_2_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  right_sdh_finger_23_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_sdh_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  head_neck_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  head_neck_yaw_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  left_sdh_thumb_3_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_sdh_thumb_2_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_sdh_finger_23_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  head_head_tilt_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  head_eyes_tilt_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  left_sdh_finger_13_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0